#%RAML 1.0
title: Mule-CountryOrderFile-api
description: Country orderfiles
traits:
 error_response: !include /error-trait.raml
/countryorder:
  is: [error_response]
  get:
    queryParameters:
      region:
        required: true
        type: string
    responses:
        200:
            body:
                application/json:
                  example: !include example/response.json

                      